import turtle

def rectangle(m,n,w,h,c):
    """
    This draws a rectangle
    """
    turtle.penup()
    turtle.goto(m,n)
    turtle.pendown()
    turtle.pencolor(c)
    turtle.fillcolor(c)
    turtle.begin_fill()
    turtle.forward(w)
    turtle.left(90)
    turtle.forward(h)
    turtle.left(90)
    turtle.forward(w)
    turtle.left(90)
    turtle.forward(h)
    turtle.left(90)
    turtle.end_fill()

def frosting(m,n,w,h,c):
    """
    This draws a frosting
    """
    turtle.penup()
    turtle.goto(m,n)
    turtle.pendown()
    turtle.pencolor(c)
    turtle.fillcolor(c)
    turtle.begin_fill()
    turtle.forward(w)
    turtle.right(90)
    turtle.forward(h)
    turtle.right(90)
    turtle.forward(w)
    turtle.right(90)
    turtle.forward(h)
    turtle.right(90)
    turtle.end_fill()  

def draw_candle(x,y,h,c):
    """
    this will draw candle
    """
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()
    turtle.pencolor("black")
    turtle.fillcolor(c)
    turtle.begin_fill()
    turtle.setheading(90) 
    turtle.forward(h)
    turtle.right(90)
    turtle.forward(7) 
    turtle.right(90)
    turtle.forward(h)
    turtle.right(90)
    turtle.forward(7)
    turtle.right(90)
    turtle.end_fill()
    turtle.penup()
    turtle.forward(h)
    turtle.pendown()
    turtle.fillcolor("orange")
    turtle.begin_fill()
    turtle.setheading(60)
    turtle.forward(9)
    turtle.setheading(300)
    turtle.forward(9)
    turtle.setheading(180)
    turtle.forward(9)
    turtle.end_fill()

def toppings(x,y,c):
    """
    this will draw the toppings of the cake
    """
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()
    turtle.setheading(90)
    turtle.pencolor(c)
    turtle.fillcolor(c)
    turtle.begin_fill()
    turtle.circle(10, 180)
    turtle.end_fill()

def table(x,y,g,j,k):
    """
    the will draw the table
    """
    turtle.setheading(0)
    turtle.pencolor("black")
    turtle.penup()
    turtle.goto(-x/2,0)
    turtle.pendown()
    turtle.fillcolor(g)
    turtle.begin_fill()
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(y)
    turtle.right(90)
    turtle.forward(x)
    turtle.right(90)
    turtle.forward(y)
    turtle.right(90)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-x/2+30,-y)
    turtle.pendown()
    turtle.setheading(270)
    turtle.fillcolor(g)
    turtle.begin_fill()
    turtle.forward(j)
    turtle.right(90)
    turtle.forward(k)
    turtle.right(90)
    turtle.forward(j)
    turtle.right(90)
    turtle.end_fill()
    turtle.goto(-x/2+60,-y)
    turtle.pendown()
    turtle.setheading(270)
    turtle.fillcolor(g)
    turtle.begin_fill()
    turtle.forward(j-j/4)
    turtle.right(90)
    turtle.forward(k)
    turtle.right(90)
    turtle.forward(j-j/4)
    turtle.right(90)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(x/2-20,-y)
    turtle.pendown()
    turtle.setheading(270)
    turtle.fillcolor(g)
    turtle.begin_fill()
    turtle.forward(j)
    turtle.right(90)
    turtle.forward(k)
    turtle.right(90)
    turtle.forward(j)
    turtle.right(90)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(x/2-50,-y)
    turtle.pendown()
    turtle.setheading(270)
    turtle.fillcolor(g)
    turtle.begin_fill()
    turtle.forward(j-j/4)
    turtle.right(90)
    turtle.forward(k)
    turtle.right(90)
    turtle.forward(j-j/4)
    turtle.right(90)
    turtle.end_fill()

def draw_balloon(x,y,c):
    """
    the will draw the balloons
    """
    turtle.speed(0)
    turtle.pencolor("black")
    turtle.penup()
    turtle.goto(x,y-30)
    turtle.pendown()
    turtle.setheading(90)
    turtle.forward(80)
    turtle.setheading(0)
    turtle.fillcolor(c)
    turtle.begin_fill()
    turtle.circle(50)
    turtle.end_fill()

def main():
    turtle.bgcolor("silver")
    turtle.speed(4)
    lc1=input("Enter the color of layer 1 : ")
    lc2=input("Enter the color of layer 2 : ")
    lc3=input("Enter the color of layer 3 : ")
    lh1=int(input("Enter the height of the layer 1 (make 60-80) : "))
    lh2=lh1*0.80
    lh3=lh2*0.80
    lw1=int(input("Enter the width of the layer 1 (make btw 200-250): "))# should be greater than height
    lw2=lw1*0.75
    lw3=lw2*0.75
    c1=input("Enter the strip color of layer 1 : ")
    c2=input("Enter the strip color of layer 2 : ")
    c3=input("Enter the strip color of layer 3 : ")
    c4=input("Enter the frosting : ")
    rectangle(-lw1/2,0,lw1,lh1,lc1)
    rectangle(-lw1/2,lh1/3,lw1,lh1/3,c1)
    frosting(-lw1/2,lh1,lw1,lh1/8,c4)
    rectangle(-lw2/2,lh1,lw2,lh2,lc2)
    rectangle(-lw2/2,lh1+lh2/3,lw2,lh2/3,c2)
    frosting(-lw2/2,lh1+lh2,lw2,lh2/8,c4)
    rectangle(-lw3/2,lh1+lh2,lw3,lh3,lc3)
    rectangle(-lw3/2,lh1+lh2+lh3/3,lw3,lh3/3,c3)
    frosting(-lw3/2,lh1+lh2+lh3,lw3,lh3/8,c4)
    h=int(input("Enter candle height: "))
    cc=input("Enter candle color: ")
    draw_candle(-lw3/2+7,lh1+lh2+lh3,h,cc)
    draw_candle(0-3,lh1+lh2+lh3,h,cc)
    draw_candle(lw3/2-15,lh1+lh2+lh3,h,cc)
    u=input("Enter the topping 1 color: ")
    t=input("Enter the topping 2 color: ")
    r=input("Enter the topping 3 color: ")
    toppings(-lw1/2+23,lh1,u)
    toppings(10,lh1,t)
    toppings(lw1/2-5,lh1,r)
    toppings(-lw2/2+23,lh1+lh2,r)
    toppings(10,lh1+lh2,u)
    toppings(lw2/2-5,lh1+lh2,t)
    m=int(input("Enter the width of the table : "))
    p=input("Enter the color of the table : ")
    j=int(input("Enter the lenght of the table leg : "))
    k=int(input("Enter the width of the table leg : "))
    b1=input("Enter the color 1 for balloon: ")
    b2=input("Enter the color 2 for balloon: ")
    b3=input("Enter the color 3 for balloon: ")
    b4=input("Enter the color 4 for balloon: ")
    b5=input("Enter the color 5 for balloon: ")
    table(lw1+80,m,p,j,k)
    draw_balloon(300,200, b1) 
    draw_balloon(150,200, b2) 
    draw_balloon(-150,200,b3) 
    draw_balloon(-300,200,b4) 
    draw_balloon(400,50, b5) 
    draw_balloon(250,50, b2) 
    draw_balloon(-250,50, b3) 
    draw_balloon(-400,50,b4) 
    draw_balloon(500,100, b1) 
    draw_balloon(620,100, b5) 
    draw_balloon(-620,100, b2) 
    draw_balloon(-500,100, b4) 
    draw_balloon(500,-100, b1) 
    draw_balloon(620,-100,b2) 
    draw_balloon(-620,-100,b3) 
    draw_balloon(-500,-100, b5) 
    
main()
print("Happy Birthday Enjoy the Cake !! ")
turtle.done()

